<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>hjson</string>
  </array>
  <key>foldingStartMarker</key>
  <string>(?x:     # turn on extended mode
    ^    # a line beginning with
    \s*    # some optional space
    [{\[]  # the start of an object or array
    (?!    # but not followed by
    .*   # whatever
    [}\]]  # and the close of an object or array
    ,?   # an optional comma
    \s*  # some optional space
    $    # at the end of the line
    )
    |    # ...or...
    [{\[]  # the start of an object or array
    \s*    # some optional space
    $    # at the end of the line
  )</string>
  <key>foldingStopMarker</key>
  <string>(?x:   # turn on extended mode
    ^    # a line beginning with
    \s*  # some optional space
    [}\]]  # and the close of an object or array
  )</string>
  <key>keyEquivalent</key>
  <string>^~J</string>
  <key>name</key>
  <string>Hjson</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#value</string>
    </dict>
    <dict>
      <key>match</key>
      <string>[^\s]</string>
      <key>name</key>
      <string>invalid.illegal.excess-characters.hjson</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>array</key>
    <dict>
      <key>begin</key>
      <string>\[</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.array.begin.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\])(?:\s*([^,\s]+))?</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.array.end.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.value.hjson</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.structure.array.hjson</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#arrayContent</string>
        </dict>
      </array>
    </dict>
    <key>arrayArray</key>
    <dict>
      <key>begin</key>
      <string>\[</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.array.begin.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\])(?:\s*([^,\s\]]+))?</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.array.end.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.value.hjson</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.structure.array.hjson</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#arrayContent</string>
        </dict>
      </array>
    </dict>
    <key>arrayConstant</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>constant.language.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.array.after-const.hjson</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(true|false|null)(?:[\t ]*(?=,)|[\t ]*(?:(,)[\t ]*)?(?=$|#|/\*|//|\]))</string>
    </dict>
    <key>arrayContent</key>
    <dict>
      <key>name</key>
      <string>meta.structure.array.hjson</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#arrayValue</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;=\[)|,</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.dictionary.pair.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=[^\s,/#])|(?=/[^/*])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comments</string>
            </dict>
            <dict>
              <key>match</key>
              <string>,</string>
              <key>name</key>
              <string>invalid.illegal.extra-comma.hjson</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>match</key>
          <string>,</string>
          <key>name</key>
          <string>punctuation.separator.array.hjson</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[^\s\]]</string>
          <key>name</key>
          <string>invalid.illegal.expected-array-separator.hjson</string>
        </dict>
      </array>
    </dict>
    <key>arrayJstring</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>"</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(")(?:\s*((?:[^,\s\]#/]|/[^/*])+))?</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.hjson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.value.hjson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.hjson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#jstringDoubleContent</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>'</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(')(?:\s*((?:[^,\s\]#/]|/[^/*])+))?</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.hjson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.value.hjson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.single.hjson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#jstringSingleContent</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>arrayMstring</key>
    <dict>
      <key>begin</key>
      <string>'''</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(''')(?:\s*((?:[^,\s\]#/]|/[^/*])+))?</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.value.hjson</string>
        </dict>
      </dict>
      <key>name</key>
      <string>string.quoted.multiline.hjson</string>
    </dict>
    <key>arrayNumber</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>constant.numeric.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.array.after-num.hjson</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(-?(?:0|(?:[1-9]\d*))(?:\.\d+)?(?:[eE][+-]?\d+)?)(?:[\t ]*(?=,)|[\t ]*(?:(,)[\t ]*)?(?=$|#|/\*|//|\]))</string>
    </dict>
    <key>arrayObject</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.begin.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\}|(?&lt;=\}))(?:\s*([^,\s\]]+))?</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.end.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.value.hjson</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.structure.dictionary.hjson</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#objectContent</string>
        </dict>
      </array>
    </dict>
    <key>arrayString</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#arrayMstring</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#arrayJstring</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ustring</string>
        </dict>
      </array>
    </dict>
    <key>arrayValue</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#arrayNumber</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#arrayConstant</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#arrayString</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#arrayObject</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#arrayArray</string>
        </dict>
      </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>match</key>
          <string>^\s*(#).*(?:\n)?</string>
          <key>name</key>
          <string>comment.line.hash</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>match</key>
          <string>^\s*(//).*(?:\n)?</string>
          <key>name</key>
          <string>comment.line.double-slash</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>^\s*/\*</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\*/(?:\s*\n)?</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>comment.block.double-slash</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>match</key>
          <string>(#)[^\n]*</string>
          <key>name</key>
          <string>comment.line.hash</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>match</key>
          <string>(//)[^\n]*</string>
          <key>name</key>
          <string>comment.line.double-slash</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>/\*</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\*/</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>comment.block.double-slash</string>
        </dict>
      </array>
    </dict>
    <key>commentsNewline</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>match</key>
          <string>(#).*\n</string>
          <key>name</key>
          <string>comment.line.hash</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>match</key>
          <string>(//).*\n</string>
          <key>name</key>
          <string>comment.line.double-slash</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>/\*</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\*/(\s*\n)?</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.hjson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>comment.block.double-slash</string>
        </dict>
      </array>
    </dict>
    <key>constant</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>constant.language.hjson</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(true|false|null)[\t ]*(?=$|#|/\*|//|\])</string>
    </dict>
    <key>jstring</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>"</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(")(?:\s*((?:[^\s#/]|/[^/*]).*)$)?</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.hjson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.value.hjson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.hjson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#jstringDoubleContent</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>'</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(')(?:\s*((?:[^\s#/]|/[^/*]).*)$)?</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.hjson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.value.hjson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.single.hjson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#jstringSingleContent</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>jstringDoubleContent</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\(?:["'\\\/bfnrt]|u[0-9a-fA-F]{4})</string>
          <key>name</key>
          <string>constant.character.escape.hjson</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\\.</string>
          <key>name</key>
          <string>invalid.illegal.unrecognized-string-escape.hjson</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[^"]*[^\n\r"\\]$</string>
          <key>name</key>
          <string>invalid.illegal.string.hjson</string>
        </dict>
      </array>
    </dict>
    <key>jstringSingleContent</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\(?:["'\\\/bfnrt]|u[0-9a-fA-F]{4})</string>
          <key>name</key>
          <string>constant.character.escape.hjson</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\\.</string>
          <key>name</key>
          <string>invalid.illegal.unrecognized-string-escape.hjson</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[^']*[^\n\r'\\]$</string>
          <key>name</key>
          <string>invalid.illegal.string.hjson</string>
        </dict>
      </array>
    </dict>
    <key>key</key>
    <dict>
      <key>begin</key>
      <string>(?x:
        (
          (?:[^:,\{\}\[\]\s"'][^:,\{\}\[\]\s]*) |
          (?: # json string w/ '
            '
            (?:
              [^\\'] | # anything but an escape character or quote
              (\\(?:["'\\\/bfnrt]|u[0-9a-fA-F]{4})) | # escape characters
              (\\.) # bad escape characters
            )*
            '
          ) |
          (?: # json string w/ "
            "
            (?:
              [^\\"] | # anything but an escape character or quote
              (\\(?:["'\\\/bfnrt]|u[0-9a-fA-F]{4})) | # escape characters
              (\\.) # bad escape characters
            )*
            "
          )
        )
        \s*
        (?!\n)
        ([,\{\}\[\]]*)
      )</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>meta.structure.key-value.begin.hjson</string>
        </dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>support.type.property-name.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.hjson</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.unrecognized-string-escape.hjson</string>
        </dict>
        <key>4</key>
        <dict>
          <key>name</key>
          <string>constant.character.escape.hjson</string>
        </dict>
        <key>5</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.unrecognized-string-escape.hjson</string>
        </dict>
        <key>6</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.separator.hjson</string>
        </dict>
        <key>7</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.property-name.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?&lt;!^|:)\s*\n|(?=})|(,)</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.dictionary.pair.hjson</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#commentsNewline</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#keyValue</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[^\s]</string>
          <key>name</key>
          <string>invalid.illegal.object-property.hjson</string>
        </dict>
      </array>
    </dict>
    <key>keyValue</key>
    <dict>
      <key>begin</key>
      <string>(?x:
        \s*
        (:)
        \s* # capture the line ending if there is no value on the same line
        ([,\}\]]*)
      )</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.dictionary.key-value.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.object-property.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?&lt;!^)\s*(?=\n)|(?=[},])</string>
      <key>name</key>
      <string>meta.structure.key-value.hjson</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>match</key>
          <string>^\s+</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#objectValue</string>
        </dict>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.object-property.closing-bracket.hjson</string>
            </dict>
          </dict>
          <key>match</key>
          <string>^\s*(\})</string>
        </dict>
        <dict>
          <key>match</key>
          <string>[^\s]</string>
          <key>name</key>
          <string>invalid.illegal.object-property.hjson</string>
        </dict>
      </array>
    </dict>
    <key>mstring</key>
    <dict>
      <key>begin</key>
      <string>'''</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(''')(?:\s*((?:[^\s#/]|/[^/*]).*)$)?</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.value.hjson</string>
        </dict>
      </dict>
      <key>name</key>
      <string>string.quoted.multiline.hjson</string>
    </dict>
    <key>number</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>constant.numeric.hjson</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(-?(?:0|(?:[1-9]\d*))(?:\.\d+)?(?:[eE][+-]?\d+)?)[\t ]*(?=$|#|/\*|//|\])</string>
    </dict>
    <key>object</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.begin.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\}|(?&lt;=\}))(?:\s*([^,\s]+))?</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.end.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.value.hjson</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.structure.dictionary.hjson</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#objectContent</string>
        </dict>
      </array>
    </dict>
    <key>objectArray</key>
    <dict>
      <key>begin</key>
      <string>\[</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.array.begin.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\])(?:\s*([^,\s\}]+))?</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.array.end.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.value.hjson</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.structure.array.hjson</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#arrayContent</string>
        </dict>
      </array>
    </dict>
    <key>objectConstant</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>constant.language.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.dictionary.pair.after-const.hjson</string>
        </dict>
      </dict>
      <key>match</key>
      <string>\b(true|false|null)(?:[\t ]*(?=,)|[\t ]*(?:(,)[\t ]*)?(?=$|#|/\*|//|\}))</string>
    </dict>
    <key>objectContent</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#key</string>
        </dict>
        <dict>
          <key>match</key>
          <string>:[.|\s]</string>
          <key>name</key>
          <string>invalid.illegal.object-property.hjson</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(?&lt;=\{|,)|,</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.separator.dictionary.pair.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=[^\s,/#])|(?=/[^/*])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comments</string>
            </dict>
            <dict>
              <key>match</key>
              <string>,</string>
              <key>name</key>
              <string>invalid.illegal.extra-comma.hjson</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>match</key>
          <string>[^\s]</string>
          <key>name</key>
          <string>invalid.illegal.object-property.hjson</string>
        </dict>
      </array>
    </dict>
    <key>objectJstring</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>"</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(")(?:\s*((?:[^,\s\}#/]|/[^/*])+))?</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.hjson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.value.hjson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.hjson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#jstringDoubleContent</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>begin</key>
          <string>'</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.hjson</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(')(?:\s*((?:[^,\s\}#/]|/[^/*])+))?</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.hjson</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal.value.hjson</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.single.hjson</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#jstringSingleContent</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>objectMstring</key>
    <dict>
      <key>begin</key>
      <string>'''</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(''')(?:\s*((?:[^,\s\}#/]|/[^/*])+))?</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.value.hjson</string>
        </dict>
      </dict>
      <key>name</key>
      <string>string.quoted.multiline.hjson</string>
    </dict>
    <key>objectNumber</key>
    <dict>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>constant.numeric.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.dictionary.pair.after-num.hjson</string>
        </dict>
      </dict>
      <key>match</key>
      <string>(-?(?:0|(?:[1-9]\d*))(?:\.\d+)?(?:[eE][+-]?\d+)?)(?:[\t ]*(?=,)|[\t ]*(?:(,)[\t ]*)?(?=$|#|/\*|//|\}))</string>
    </dict>
    <key>objectObject</key>
    <dict>
      <key>begin</key>
      <string>\{</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.begin.hjson</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\}|(?&lt;=\})\}?)(?:\s*([^,\s}]+))?</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.dictionary.end.hjson</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>invalid.illegal.value.hjson</string>
        </dict>
      </dict>
      <key>name</key>
      <string>meta.structure.dictionary.hjson</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#objectContent</string>
        </dict>
      </array>
    </dict>
    <key>objectString</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#objectMstring</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#objectJstring</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ustring</string>
        </dict>
      </array>
    </dict>
    <key>objectValue</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#objectNumber</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#objectConstant</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#objectString</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#objectObject</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#objectArray</string>
        </dict>
      </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#mstring</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#jstring</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#ustring</string>
        </dict>
      </array>
    </dict>
    <key>ustring</key>
    <dict>
      <key>match</key>
      <string>([^:,\{\[\}\]\s].*)$</string>
      <key>name</key>
      <string>string.quoted.none.hjson</string>
    </dict>
    <key>value</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#number</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#constant</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#object</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#array</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>scopeName</key>
  <string>source.hjson</string>
</dict>
</plist>
